apiVersion: batch/v1
kind: CronJob
metadata:
  name: elasticsearch-snapshot
  namespace: default
  labels:
    app: elasticsearch-snapshot
    version: v1.0.0
spec:
  schedule: "0 2 * * *"  # Run daily at 2:00 AM
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: elasticsearch-snapshot
        spec:
          restartPolicy: OnFailure
          containers:
          - name: snapshot
            image: your-registry/elasticsearch-snapshot:latest
            imagePullPolicy: Always
            env:
            # Elasticsearch Configuration
            - name: SNAPSHOT_HOSTS
              value: "http://elasticsearch-service:9200"
            - name: SNAPSHOT_USERNAME
              value: "elastic"
            - name: SNAPSHOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-secret
                  key: password
            - name: SNAPSHOT_VERIFY_CERTS
              value: "false"
            
            # Repository Configuration
            - name: ES_REPOSITORY_NAME
              value: "s3_backup"
            - name: ES_INDICES
              value: "*"
            
            # S3 Configuration
            - name: S3_BUCKET_NAME
              value: "your-s3-bucket"
            - name: S3_BASE_PATH
              value: "elasticsearch-snapshots"
            - name: S3_REGION
              value: "us-east-1"
            - name: S3_ENDPOINT
              value: "https://s3.amazonaws.com"
            - name: S3_PROTOCOL
              value: "https"
            - name: S3_PATH_STYLE_ACCESS
              value: "false"
            
            # AWS Credentials
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: secret-access-key